### ISSUE TITLE
node_modules/@use-it/interval/types/index.d.ts' is not a module.ts

### ISSUE THREAD

**Issue by michaelsync** [donavon/use-interval#1]
Hi,

I am using @use-it/interval yarn package in my react + typescript project. 

` yarn add @use-it/interval`

When I import it as below, I got this 'File: node_modules/@use-it/interval/types/index.d.ts' is not a module.ts'

`import useInterval from '@use-it/interval';`

It fixes the error when I change `declare module '@use-it/use-interval` to this `declare module '@use-it/interval` which I don't want to do. 

Is it the known issue?

**Comment by donavon** [comment]
fixed and published as v0.1.2. thank for reporting

**Comment by michaelsync** [comment]
@donavon Thanks. I just tested the new version 0.1.2 . 

I got this error 'Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)'

![image](https://user-images.githubusercontent.com/192911/55957418-a9d44500-5ca9-11e9-9ef2-b1e8cbeefd56.png)

I got the same react and react-dom version. 

`
{
  "name": "react-map-sample",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@react-google-maps/api": "^1.1.0",
    "@types/googlemaps": "^3.30.19",
    "@use-it/interval": "^0.1.2",
    "bootstrap": "^4.3.1",
    "json-typescript-mapper": "^1.1.3",
    "react": "^16.8.4",
    "react-bootstrap": "^1.0.0-beta.5",
    "react-dom": "^16.8.4",
    "react-router": "^5.0.0",
    "react-router-dom": "^5.0.0",
    "react-scripts-ts": "3.1.0",
    "whatwg-fetch": "^3.0.0"
  },
  "scripts": {
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  },
  "devDependencies": {
    "@types/bootstrap": "^4.3.0",
    "@types/jest": "^24.0.11",
    "@types/node": "^11.11.3",
    "@types/react": "^16.8.8",
    "@types/react-dom": "^16.8.2",
    "@types/react-router-dom": "^4.3.1",
    "typescript": "^3.3.3333"
  }
}

`

**Comment by donavon** [comment]
@michaelsync 

The sample app at https://codesandbox.io/s/2n542qnzr is working and the tests (there are many) are all passing. Can you link to a sample CodeSandbox that shows your error so I can help?

Thx

**Comment by michaelsync** [comment]
Thanks. It seems like I got my local node_module issue. It works in new Sandbox and new local test. Thanks

**Comment by donavon** [comment]
@all-contributors please add @michaelsync for bug
