### ISSUE TITLE
Missing the ability to stop the Interval

### ISSUE THREAD

**Issue by patroza** [donavon/use-interval#10]
The interval is currently connected to the component lifecycle, however some intervals should quit earlier.
We can either track a boolean and skip executing the code in the interval, or e.g create a separate component with the useInterval and conditionally render it.
Both seem to be inelegant.

**Comment by kawamurakazushi** [comment]
@patroza 
Sorry if I misunderstood, but you can stop the interval by setting the delay to `null`.

```tsx
const Root: FC = () => {
  const [remaining, setRemaining] = useState(25);
  const [delay, setDelay] = useState<number | null>(1000);

  useInterval(() => {
    setRemaining(remaining - 1);
  }, delay);

  return (
    <>
      <button
        onClick={() => {
          setDelay(null);
        }}
      >
        stop
      </button>
    </>
  );
};

```

**Comment by h0jeZvgoxFepBQ2C** [comment]
Also explained here: https://overreacted.io/making-setinterval-declarative-with-react-hooks/
