### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by AjaxSolutions** [donavon/use-interval#11]
I'm just trying to understand the code.  Why the callback is not saved by passing it directly to useRef?  Why useEffect is used to save the callback?

`const savedCallback = useRef(callback);`

**Comment by AjaxSolutions** [comment]
I see, this is so the callback can be changed.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Also see here the background: https://overreacted.io/making-setinterval-declarative-with-react-hooks/
